In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

x = np.array([[0,0], [0,1],[1,0],[1,1]])
y = np.array([0,1,1,0]).reshape(-1,1)
lr= 0.1

weights1 = np.random.random((2,4))
weights2 = np.random.random((4,1))

def sigmoid(x):
    return (1/(1+np.exp(-x)))

def turev(x):
    return x*(1-x)

print(x.shape)
print(y.shape)

(4, 2)
(4, 1)


In [7]:
for i in range(10000):
    #feed forward
    z1 = np.dot(x,weights1)
    a1 = sigmoid(z1)
    z2 = np.dot(a1,weights2)
    a2 = sigmoid(z2)
    
    #loss
    hata = y - a2
    
    # back propagation
    da2 = hata * turev(a2)
    l1error  = da2.dot(weights2.T)
    da1 = l1error *turev(a1)
    
    #updating weights
    weights2 += lr * np.dot(a1.T, da2)
    weights1 += lr * np.dot(x.T,da1)

print(f"tahmini sonuc:\n {(a2>0.5).astype(int)}, \n weights1:\n {weights1}, \n weights2 :\n {weights2}")

tahmini sonuc:
 [[0]
 [1]
 [1]
 [0]], 
 weights1:
 [[ 5.02462735  1.63513538 -2.88100752  5.0449393 ]
 [ 5.06654432 -1.02451421  5.74737342 -2.48412866]], 
 weights2 :
 [[10.93256961]
 [-2.80862267]
 [-7.10397348]
 [-5.61795701]]


In [8]:
df = pd.DataFrame(y)
df["a2"] = a2.round(2)
df["a2."] = (a2>0.5).astype(int)
df["y"] = y
df.drop(0, axis=1)

a2  a2.  y
0  0.09    0  0
1  0.93    1  1
2  0.93    1  1
3  0.06    0  0